<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>twisted.python.log.LogPublisher._err : API documentation</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>
    <h1 class="method private">t.p.l.L._err(self, failure, why) : method documentation</h1>
    <p>
      <span id="part">Part of <a href="twisted.html">twisted</a>.<a href="twisted.python.html">python</a>.<a href="twisted.python.log.html">log</a>.<a href="twisted.python.log.LogPublisher.html">LogPublisher</a></span>
      <a href="http://twistedmatrix.com/trac/browser/tags/releases/twisted-15.1.0/twisted/python/log.py#L224">View Source</a>
      
    </p>
    <div>
      
    </div>
    <div class="docstring">
      <div><p>Log a failure.</p>
<p>Similar in functionality to the global {err} function, but the failure 
gets published only to observers attached to this publisher.</p><table class="fieldTable"><tr class="fieldStart"><td class="fieldName">Parameters</td><td class="fieldArg">failure</td><td>The failure to log. (type: <a href="twisted.python.failure.Failure.html"><code>Failure</code></a>.)</td></tr><tr><td></td><td class="fieldArg">why</td><td>The source of this failure.  This will be logged along with the 
<code>failure</code> and should describe the context in which the failure 
occurred. (type: <code>str</code>)</td></tr></table></div>
    </div>

    
    <div id="splitTables">
      
      
    </div>
    
    

    
    <address>
      <a href="index.html">API Documentation</a> for <a href="http://twistedmatrix.com/">Twisted</a>, generated by <a href="https://launchpad.net/pydoctor/">pydoctor</a> at 2015-04-13 15:26:48.
    </address>
  </body>
</html>