<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>twisted.spread.pb.CopiedFailure.throwExceptionIntoGenerator : API documentation</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>
    <h1 class="method">t.s.p.C.throwExceptionIntoGenerator(self, g) : method documentation</h1>
    <p>
      <span id="part">Part of <a href="twisted.html">twisted</a>.<a href="twisted.spread.html">spread</a>.<a href="twisted.spread.pb.html">pb</a>.<a href="twisted.spread.pb.CopiedFailure.html">CopiedFailure</a></span>
      <a href="http://twistedmatrix.com/trac/browser/tags/releases/twisted-15.1.0/twisted/spread/pb.py#L457">View Source</a>
      
    </p>
    <div>
      
    </div>
    <div class="docstring">
      <div><p>Throw the original exception into the given generator, preserving 
traceback information if available. In the case of a <a href="twisted.spread.pb.CopiedFailure.html"><code>CopiedFailure</code></a> 
where the exception type is a string, a <a href="twisted.spread.pb.RemoteError.html"><code>pb.RemoteError</code></a> 
is thrown instead.</p><table class="fieldTable"><tr class="fieldStart"><td class="fieldName">Returns</td><td colspan="2">The next value yielded from the generator.</td></tr><tr class="fieldStart"><td class="fieldName">Raises</td><td class="fieldArg">StopIteration</td><td>If there are no more values in the generator.</td></tr><tr><td></td><td class="fieldArg">RemoteError</td><td>The wrapped remote exception.</td></tr></table></div>
    </div>

    
    <div id="splitTables">
      
      
    </div>
    
    

    
    <address>
      <a href="index.html">API Documentation</a> for <a href="http://twistedmatrix.com/">Twisted</a>, generated by <a href="https://launchpad.net/pydoctor/">pydoctor</a> at 2015-04-13 15:26:48.
    </address>
  </body>
</html>