<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>twisted.internet.defer.Deferred.errback : API documentation</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>
    <h1 class="method">t.i.d.D.errback(self, fail=None) : method documentation</h1>
    <p>
      <span id="part">Part of <a href="twisted.html">twisted</a>.<a href="twisted.internet.html">internet</a>.<a href="twisted.internet.defer.html">defer</a>.<a href="twisted.internet.defer.Deferred.html">Deferred</a></span>
      <a href="http://twistedmatrix.com/trac/browser/tags/releases/twisted-15.1.0/twisted/internet/defer.py#L386">View Source</a>
      
    </p>
    <div>
      
    </div>
    <div class="docstring">
      <div><p>Run all error callbacks that have been added to this <a href="twisted.internet.defer.Deferred.html"><code>Deferred</code></a>.</p>
<p>Each callback will have its result passed as the first argument to the 
next; this way, the callbacks act as a 'processing chain'. Also, if the 
error-callback returns a non-Failure or doesn't raise an <a href="http://docs.python.org/library/exceptions.html#exceptions.Exception"><code>Exception</code></a>,
processing will continue on the *success*-callback chain.</p>
<p>If the argument that's passed to me is not a <a href="twisted.python.failure.Failure.html"><code>failure.Failure</code></a>
instance, it will be embedded in one. If no argument is passed, a <a href="twisted.python.failure.Failure.html"><code>failure.Failure</code></a>
instance will be created based on the current traceback stack.</p>
<p>Passing a string as `fail' is deprecated, and will be punished with a 
warning message.</p>
<p>An instance of <a href="twisted.internet.defer.Deferred.html"><code>Deferred</code></a> may 
only have either <a href="twisted.internet.defer.Deferred.html#callback"><code>callback</code></a>
or <a href="twisted.internet.defer.Deferred.html#errback"><code>errback</code></a>
called on it, and only once.</p><table class="fieldTable"><tr class="fieldStart"><td class="fieldName">Parameters</td><td class="fieldArg">fail</td><td>The <a href="twisted.python.failure.Failure.html"><code>Failure</code></a> 
object which will be passed to the first errback added to this <a href="twisted.internet.defer.Deferred.html"><code>Deferred</code></a> (via 
<a href="twisted.internet.defer.Deferred.html#addErrback"><code>addErrback</code></a>).
Alternatively, a <a href="http://docs.python.org/library/exceptions.html#exceptions.Exception"><code>Exception</code></a>
instance from which a <a href="twisted.python.failure.Failure.html"><code>Failure</code></a> will be
constructed (with no traceback) or <code>None</code> to create a <a href="twisted.python.failure.Failure.html"><code>Failure</code></a> 
instance from the current exception state (with a traceback).</td></tr><tr class="fieldStart"><td class="fieldName">Raises</td><td class="fieldArg">AlreadyCalledError</td><td>If <a href="twisted.internet.defer.Deferred.html#callback"><code>callback</code></a>
or <a href="twisted.internet.defer.Deferred.html#errback"><code>errback</code></a>
has already been called on this <a href="twisted.internet.defer.Deferred.html"><code>Deferred</code></a>.</td></tr><tr><td></td><td class="fieldArg">NoCurrentExceptionError</td><td>If <code>fail</code> is <code>None</code> but there is no current exception
state.</td></tr></table></div>
    </div>

    
    <div id="splitTables">
      
      
    </div>
    
    

    
    <address>
      <a href="index.html">API Documentation</a> for <a href="http://twistedmatrix.com/">Twisted</a>, generated by <a href="https://launchpad.net/pydoctor/">pydoctor</a> at 2015-04-13 15:26:48.
    </address>
  </body>
</html>