<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>twisted.internet.defer.returnValue : API documentation</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>
    <h1 class="function">t.i.d.returnValue(val) : function documentation</h1>
    <p>
      <span id="part">Part of <a href="twisted.html">twisted</a>.<a href="twisted.internet.html">internet</a>.<a href="twisted.internet.defer.html">defer</a></span>
      <a href="http://twistedmatrix.com/trac/browser/tags/releases/twisted-15.1.0/twisted/internet/defer.py#L1071">View Source</a>
      
    </p>
    <div>
      
    </div>
    <div class="docstring">
      <div><p>Return val from a <a href="twisted.internet.defer.html#inlineCallbacks"><code>inlineCallbacks</code></a>
generator.</p>
<p>Note: this is currently implemented by raising an exception derived from
<a href="http://docs.python.org/library/exceptions.html#exceptions.BaseException"><code>BaseException</code></a>.
You might want to change any 'except:' clauses to an 'except Exception:' 
clause so as not to catch this exception.</p>
<p>Also: while this function currently will work when called from within 
arbitrary functions called from within the generator, do not rely upon this
behavior.</p><table class="fieldTable"></table></div>
    </div>

    
    <div id="splitTables">
      
      
    </div>
    
    

    
    <address>
      <a href="index.html">API Documentation</a> for <a href="http://twistedmatrix.com/">Twisted</a>, generated by <a href="https://launchpad.net/pydoctor/">pydoctor</a> at 2015-04-13 15:26:48.
    </address>
  </body>
</html>