<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>twisted.mail.pop3.POP3.state_AUTH : API documentation</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>
    <h1 class="method">t.m.p.P.state_AUTH(self, line) : method documentation</h1>
    <p>
      <span id="part">Part of <a href="twisted.html">twisted</a>.<a href="twisted.mail.html">mail</a>.<a href="twisted.mail.pop3.html">pop3</a>.<a href="twisted.mail.pop3.POP3.html">POP3</a></span>
      <a href="http://twistedmatrix.com/trac/browser/tags/releases/twisted-15.1.0/twisted/mail/pop3.py#L730">View Source</a>
      
    </p>
    <div>
      
    </div>
    <div class="docstring">
      <div><p>Handle received lines for the AUTH state in which an authentication 
challenge response from the client is expected.</p>
<p>Transition back to the COMMAND state.  Check the credentials and 
complete the authorization process with the <a href="twisted.mail.pop3.POP3.html#_cbMailbox"><code>_cbMailbox</code></a> 
callback function on success or the <a href="twisted.mail.pop3.POP3.html#_ebMailbox"><code>_ebMailbox</code></a> 
and <a href="twisted.mail.pop3.POP3.html#_ebUnexpected"><code>_ebUnexpected</code></a>
errback functions on failure.</p><table class="fieldTable"><tr class="fieldStart"><td class="fieldName">Parameters</td><td class="fieldArg">line</td><td>The challenge response. (type: <a href="http://docs.python.org/library/stdtypes.html#bytes"><code>bytes</code></a>)</td></tr></table></div>
    </div>

    
    <div id="splitTables">
      
      
    </div>
    
    

    
    <address>
      <a href="index.html">API Documentation</a> for <a href="http://twistedmatrix.com/">Twisted</a>, generated by <a href="https://launchpad.net/pydoctor/">pydoctor</a> at 2015-04-13 15:26:48.
    </address>
  </body>
</html>