<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>API docs for &ldquo;twisted.internet.defer.fail&rdquo;</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>
    <h1 class="function">Function t.i.d.fail(result=None):</h1>
    <p>
      <span id="part">Part of <a href="twisted.html">twisted</a>.<a href="twisted.internet.html">internet</a>.<a href="twisted.internet.defer.html">defer</a></span>
      <a href="http://twistedmatrix.com/trac/browser/tags/releases/twisted-8.1.0/twisted/internet/defer.py#L52">View Source</a>
      
    </p>
    <div>
      
    </div>
    <div><p>Return a Deferred that has already had '.errback(result)' called.</p>
See <a 
href="twisted.internet.defer.html#succeed"><code>succeed</code></a>'s 
docstring for rationale.
<table class="fieldTable"><tr class="fieldStart"><td class="fieldName">Parameters</td><td class="fieldArg">result</td><td>The same argument that <a 
href="twisted.internet.defer.Deferred.html#errback"><code>Deferred.errback</code></a> 
takes.
</td></tr><tr class="fieldStart"><td class="fieldName">Returns</td><td colspan="2"> (type: <a 
href="twisted.internet.defer.Deferred.html"><code>Deferred</code></a>
)</td></tr><tr class="fieldStart"><td class="fieldName">Raises</td><td class="fieldArg">NoCurrentExceptionError</td><td>If <code>result</code> is <code>None</code> but there is no current 
exception state.
</td></tr></table></div>
    
    
    <div id="splitTables">
      
      
      
    </div>
    
    
    
    
    
    <address>
      <a href="index.html">API Documentation</a> for <a href="http://twistedmatrix.com/trac">Twisted</a>, generated by <a href="http://codespeak.net/~mwh/pydoctor/">pydoctor</a> at 2008-05-18 16:50:21.
    </address>
  </body>
</html>