<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>twisted.spread.pb.Error : API documentation</title>

    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link rel="stylesheet" href="bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="apidocs.css" type="text/css" />
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a href="index.html" class="navbar-brand">
            Twisted API Documentation
          </a>
        </div>
      </div>
    </nav>

   <div class="container" id="current-docs-container" style="display: none">
      <div class="col-sm-12">
        <a id="current-docs-link">
          Go to the latest version of this document.
        </a>
      </div>
    </div>

    <div id="showPrivate">
      <button onclick="togglePrivate()" class="btn btn-link">Toggle Private API</button>
    </div>

    <div class="container">

      <div class="page-header">
        <h1 class="class"><code>twisted.spread.pb.Error(<span title="Exception">Exception</span>)</code> <small>class documentation</small></h1>

        <span id="partOf">
          Part of <code><a href="twisted.html" data-type="Package" class="code">twisted</a>.<a href="twisted.spread.html" data-type="Package" class="code">spread</a>.<a href="twisted.spread.pb.html" data-type="Module" class="code">pb</a></code>
          <a href="https://github.com/twisted/twisted/tree/twisted-18.9.0/src/twisted/spread/pb.py#L96">View Source</a>
          <a href="classIndex.html#twisted.spread.pb.Error">(View In Hierarchy)</a>
        </span>
      </div>

      <div class="extrasDocstring">
        
      </div>

      

      <div class="moduleDocstring">
        <div><p>This error can be raised to generate known error conditions.</p>
<p>When a PB callable method (perspective_, remote_, view_) raises this 
error, it indicates that a traceback should not be printed, but instead, 
the string representation of the exception should be sent.</p><table class="fieldTable"></table></div>
      </div>

      <div id="splitTables">
        
        

          
      </div>

      <div id="childList">

        

      </div>
      <address>
        <a href="index.html">API Documentation</a> for <a href="http://twistedmatrix.com/">Twisted</a>, generated by <a href="https://github.com/twisted/pydoctor/">pydoctor</a> at 2018-10-15 19:29:43.
      </address>

    </div>

    <script src="pydoctor.js" type="text/javascript"></script>

    <!-- Google analytics, obviously. -->
    <script src="//www.google-analytics.com/urchin.js" type="text/javascript"></script>
    <script type="text/javascript">
      _uacct = "UA-99018-6";
      urchinTracker();
    </script>

    <!-- If the documentation isn't current, insert a current link. -->
    <script type="text/javascript">
      if (window.location.pathname.indexOf('/current/') == -1) {
        <!-- Give the user a link to this page, but in the current version of the docs. -->
        var link = document.getElementById('current-docs-link');
        link.href = window.location.pathname.replace(/\/\d+\.\d+\.\d+\/api\//, '/current/api/');
        <!-- And make it visible -->
        var container = document.getElementById('current-docs-container');
        container.style.display = "";
        delete link;
        delete container;
      }
    </script>

  </body>
</html>